# Generated by Django 2.0.2 on 2018-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('color', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'OrderStatus',
                'verbose_name_plural': 'OrderStatuses',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
    ]
