# Generated by Django 2.0.2 on 2018-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180223_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='deliverySum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
    ]
