# Generated by Django 2.0.2 on 2018-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180223_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=140, unique=True)),
                ('value', models.CharField(default='', max_length=140)),
                ('comment', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
