# Generated by Django 2.0.2 on 2018-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180317_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
