# Generated by Django 2.0.2 on 2018-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_invoice_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='multiplicity',
            field=models.IntegerField(default=1),
        ),
    ]
