# Generated by Django 2.0.2 on 2018-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='trackNumber',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
    ]
