# Generated by Django 2.0.2 on 2018-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_invoice_tracknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='personInChargePhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='personRecipient',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='personRecipientPhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
